[package]
name = "panmath"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.0.0"
lazy_static = "1.4.0"
strum = "0.22"
strum_macros = "0.22"
